name: update_center
description: "A package that allows you to implement your own update system for your application."
version: 1.0.0-beta.2+1
homepage: https://github.com/Smolla-ITc/update_center
issue_tracker: https://github.com/Smolla-ITc/update_center/issues

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  http: ^1.2.1
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  flutter_local_notifications: ^17.1.0
  permission_handler: ^11.3.1
  open_filex: ^4.4.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

assets:
    - assets/

flutter:
  plugin:
    platforms:
      android:
        package: com.smollaitc.update_center
        pluginClass: UpdateCenterPlugin
      ios:
        pluginClass: UpdateCenterPlugin
      windows:
        pluginClass: UpdateCenterPluginCApi