name: update_center
description: "A package that allows you to implement your own update system for your application."
version: 2.0.0
homepage: https://github.com/Smolla-ITc/update_center
issue_tracker: https://github.com/Smolla-ITc/update_center/issues

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  http: ^1.2.2
  package_info_plus: ^8.1.3
  path_provider: ^2.1.5
  open_filex: ^4.6.0
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: org.smollaitc.update_center
        pluginClass: UpdateCenterPlugin
      windows:
        pluginClass: UpdateCenterPluginCApi